### ISSUE TITLE
Add region type Census Subdivision (CSD)?

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/popApp#4]
The ability to get BC sub-population estimates by various administrative units is _very very_ useful, so thanks for keeping this App going :tada:. 

I often need estimates from multiple different administrative units for a given analysis, many I get through the BCStats App. I often need Census Subdivision, which I source directly from Statistics Canada, e.g. CSD (Census Subdivision) [Statistics Canada (Table: 17-10-0142-01)](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710014201). I was thinking an enhancement to the App might be to include regional B.C. population estimates by CD and/or CSD.

**Comment by MonkmanMH** [comment]
Another geographic unit to consider:
Population Centre and Rural Area Classification 2016
https://www.statcan.gc.ca/eng/subjects/standard/pcrac/2016/introduction

**Comment by MonkmanMH** [comment]
UPDATE: Please add CSD estimates and projections ... the estimates are available on the BC Stats website as an Excel file, but the projections are nowhere to be found. Much appreciated!

**Comment by stephhazlitt** [comment]
I just provided this feedback via email, but will share here as well. It would be great if _all_ the data made available through this amazing App and the [BC Stats population page](https://www2.gov.bc.ca/gov/content/data/statistics/people-population-community/population/population-estimates) were _also_ available directly from the BC Data Catalogue. Users searching the catalogue, the authoritative source of bcgov data, are left thinking this data is not available, and generally it is hard to find data distributed across so many different web real estates (apps+pages). Also, for power users, data in the catalogue is available programatically, facilitating building repeatable data workflows. This additional backend data storage step feels like an easy and low-cost change that would have a major impact on the find-ability and usability of BC Stats population data.

**Comment by stephanieyurchak** [comment]
estimates and projections are now available for municipalities
