### ISSUE TITLE
Population estimate data by all region types in the BCDC

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/popApp#5]
The PopApp is very (very) useful for quickly looking up regional population estimates and seeing what regional population estimates are available. Once I determine what I need, my workflow has been to then source the raw data programmatically from the B.C. Data Catalogue using {bcdata}: [BC Population Estimates](https://catalogue.data.gov.bc.ca/dataset/bc-population-estimates). It would be very useful if the source estimate data was available by all the region types in the B.C. Data Catalogue.

**Comment by stephanieyurchak** [comment]
The data is now available in the BCDC here: https://catalogue.data.gov.bc.ca/dataset/bc-sub-provincial-population-estimates-and-projections
